jobs:
  - job: linux_build
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: setup-project.yml
      - script: tar -cf project.tar ./*
        displayName: 'Preparing Artifact'
      - task: CopyFiles@2
        inputs:
          contents: 'project.tar'
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(Build.ArtifactStagingDirectory)
          artifactName: project-with-deps
  - job: lint_js
    dependsOn: linux_build
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: linux-build-job.yml
      - script: |
          yarn lint:js
        displayName: 'Lint JS'
  - job: lint_hbs
    dependsOn: linux_build
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: linux-build-job.yml
      - script: |
          yarn lint:hbs
        displayName: 'Lint HBS'
  - job: tests
    dependsOn: linux_build
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: linux-build-job.yml
      - script: |
          yarn test
        displayName: 'Test'
